name: Tests

on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "app/tests/**"
      - "app/src/**"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "app/tests/**"
      - "app/src/**"

jobs:
  integration_test:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2.1.5
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: 4-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app/west.yml') }}
          restore-keys: |
            4-${{ runner.os }}-build-${{ env.cache-name }}-
            4-${{ runner.os }}-build-
            4-${{ runner.os }}-
        timeout-minutes: 2
        continue-on-error: true
      - name: Initialize workspace (west init)
        run: west init -l app
      - name: Update modules (west update)
        run: west update
      - name: Export Zephyr CMake package (west zephyr-export)
        run: west zephyr-export
      - name: Test all
        run: west test
      - name: Archive artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: "log-files"
          path: app/build/**/*.log
